// Generated by scripts/generate-local-types.js from the migration applied to PGlite PostgreSQL.
// Bootstrap snapshot; regenerate from Supabase with npm run types:generate after migration.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      prospects: {
        Row: {
          id: string;
          owner_id: string;
          company: string;
          title: string;
          job_url: string | null;
          source: string | null;
          location: string | null;
          work_arrangement: string | null;
          employment_type: string | null;
          compensation_text: string | null;
          job_description: string | null;
          posted_on: string | null;
          discovered_on: string | null;
          applied_on: string | null;
          status: string;
          notes: string | null;
          connections: Json;
          experience_fit: number | null;
          level_fit: number | null;
          compensation_fit: number | null;
          consumer_fit: number | null;
          domain_fit: number | null;
          craft_interaction_fit: number | null;
          systems_fit: number | null;
          work_style_fit: number | null;
          logistics_fit: number | null;
          relationship_strength: number | null;
          overall_assessment: number | null;
          personal_interest: number | null;
          assessment_rationale: string | null;
          assessment_concerns: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          company: string;
          title: string;
          job_url?: string | null;
          source?: string | null;
          location?: string | null;
          work_arrangement?: string | null;
          employment_type?: string | null;
          compensation_text?: string | null;
          job_description?: string | null;
          posted_on?: string | null;
          discovered_on?: string | null;
          applied_on?: string | null;
          status?: string;
          notes?: string | null;
          connections?: Json;
          experience_fit?: number | null;
          level_fit?: number | null;
          compensation_fit?: number | null;
          consumer_fit?: number | null;
          domain_fit?: number | null;
          craft_interaction_fit?: number | null;
          systems_fit?: number | null;
          work_style_fit?: number | null;
          logistics_fit?: number | null;
          relationship_strength?: number | null;
          overall_assessment?: number | null;
          personal_interest?: number | null;
          assessment_rationale?: string | null;
          assessment_concerns?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          company?: string;
          title?: string;
          job_url?: string | null;
          source?: string | null;
          location?: string | null;
          work_arrangement?: string | null;
          employment_type?: string | null;
          compensation_text?: string | null;
          job_description?: string | null;
          posted_on?: string | null;
          discovered_on?: string | null;
          applied_on?: string | null;
          status?: string;
          notes?: string | null;
          connections?: Json;
          experience_fit?: number | null;
          level_fit?: number | null;
          compensation_fit?: number | null;
          consumer_fit?: number | null;
          domain_fit?: number | null;
          craft_interaction_fit?: number | null;
          systems_fit?: number | null;
          work_style_fit?: number | null;
          logistics_fit?: number | null;
          relationship_strength?: number | null;
          overall_assessment?: number | null;
          personal_interest?: number | null;
          assessment_rationale?: string | null;
          assessment_concerns?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      prospect_status_events: {
        Row: {
          id: number;
          prospect_id: string;
          from_status: string | null;
          to_status: string;
          recorded_at: string;
        };
        Insert: {
          id?: never;
          prospect_id: string;
          from_status?: string | null;
          to_status: string;
          recorded_at?: string;
        };
        Update: {
          id?: never;
          prospect_id?: string;
          from_status?: string | null;
          to_status?: string;
          recorded_at?: string;
        };
        Relationships: [{ foreignKeyName: "prospect_status_events_prospect_id_fkey"; columns: ["prospect_id"]; isOneToOne: false; referencedRelation: "prospects"; referencedColumns: ["id"]; }];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
